global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapiapp:8000']
